warehouse {
  id = "w1"
  id = ${?WAREHOUSE_ID}

  sensors = [
    { type = TEMPERATURE, host = "0.0.0.0", port = 3344, port = ${?TEMPERATURE_PORT} },
    { type = HUMIDITY, host = "0.0.0.0", port = 3355, port = ${?HUMIDITY_PORT} }
  ]
}

nats {
  url = "nats://127.0.0.1:4222"
  url = ${?NATS_URL}

  measurement-subject = "warehouse."${warehouse.id}".measurement"
  measurement-subject = ${?MEASUREMENT_SUBJECT}
}

pekko {
  loglevel = INFO
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
}
